# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcdad67a41451d99aecc54ae098910556060c21b681d9ce089cbc925678d430507bc066aa0ea3995e2617b1189cbce174762c4bfccf3569939154fb20f683e9c

test:
  secret_key_base: cfc6570880522643eac9d21cb8ea1d2ba4399372525bdb6730bcdd5b7f4ee24c62b80c547c0353cd40a8c1a3ce8cabc46a14aa57149fc38fcb7d7001487e0003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
